### ISSUE TITLE
`matmuladd` not working with `SVectors`

### ISSUE THREAD

**Issue by lcontento** [LuxDL/LuxLib.jl#140]
Applying a `Lux.Dense` layer on `SVectors` is no longer possible (it used to be).

The problem seems to be due to newer versions of LuxLib using LoopVectorization for matrix multiplication. The input `SVector` gets reshaped and while `LoopVectorization.check_args` says that it is ok, it is actually not. `SMatrices` play instead nice with LoopVectorization.

MWE
```julia
using LuxLib
using LuxLib.Impl: matmuladd
using StaticArrays

A = rand(2, 2)
bias = rand(2)

# This works with LoopVectorization
B = ones(SMatrix{2, 1, Float64})
matmuladd(A, B, bias)

# This gets wrapped in a ReshapedArray
# and no longer works with LoopVectorization
b = ones(SVector{2, Float64})
matmuladd(A, b, bias)
```

**Comment by avik-pal** [comment]
I will take a look. For staticarrays, it should not be using LoopVectorization (the standard matmul in StaticArrays.jl is good enough).

The problem is stemming from the `internal_operation_mode` check which is not checking for wrapper types correctly.

**Comment by avik-pal** [comment]
(Writing this comment so that I dont forget) Need to write `reshape(x, :, 1)` as `<batchify>(x)` which introduces a singleton dim without creating a wrapper type for staticvector (since the size is statically inferrable)
